import './globals.css'
import { Inter } from 'next/font/google'
import Navbar from "@/components/Navbar";
import Script from "next/script";

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Car Rental',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
    <link rel="icon" href="/favicon.png"/>
    <Script src="https://kit.fontawesome.com/a388be2306.js" crossOrigin="anonymous" defer="defer"></Script>
    <body className={inter.className}>
      <div className="flex flex-col">
        <Navbar />
        {children}
      </div>
      </body>
    </html>
  )
}
